// <auto-generated />
using CityTransport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityTransport.Data.Migrations
{
    [DbContext(typeof(CityTransportContext))]
    [Migration("20250930194433_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CityTransport.Data.Models.BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndPoint = "Rachel / De Lorimier (North)",
                            Name = "De Lorimier",
                            RouteNumber = "10",
                            StartPoint = "Terminus Papineau (South)"
                        },
                        new
                        {
                            Id = 2,
                            EndPoint = "Côte-des-Neiges / Ridgewood",
                            Name = "Parc-du-Mont-Royal / Ridgewood",
                            RouteNumber = "11",
                            StartPoint = "Metro Mont-Royal"
                        },
                        new
                        {
                            Id = 3,
                            EndPoint = "Île-des-Soeurs",
                            Name = "Île-des-Soeurs",
                            RouteNumber = "12",
                            StartPoint = "Metro De l’Église"
                        },
                        new
                        {
                            Id = 4,
                            EndPoint = "Atwater",
                            Name = "Sainte-Catherine",
                            RouteNumber = "15",
                            StartPoint = "Terminus Papineau"
                        },
                        new
                        {
                            Id = 5,
                            EndPoint = "Metro Beaubien",
                            Name = "Beaubien",
                            RouteNumber = "18",
                            StartPoint = "Rosemont / Beaubien"
                        },
                        new
                        {
                            Id = 6,
                            EndPoint = "Westmount / Vendôme",
                            Name = "Sherbrooke",
                            RouteNumber = "24",
                            StartPoint = "Terminus Sherbrooke Est"
                        },
                        new
                        {
                            Id = 7,
                            EndPoint = "Henri-Bourassa / Lacordaire",
                            Name = "Lacordaire",
                            RouteNumber = "32",
                            StartPoint = "Terminus Cadillac"
                        },
                        new
                        {
                            Id = 8,
                            EndPoint = "Henri-Bourassa Est",
                            Name = "Papineau",
                            RouteNumber = "45",
                            StartPoint = "Metro Papineau"
                        },
                        new
                        {
                            Id = 9,
                            EndPoint = "Metro Snowdon",
                            Name = "Édouard-Montpetit",
                            RouteNumber = "51",
                            StartPoint = "Metro Laurier"
                        },
                        new
                        {
                            Id = 10,
                            EndPoint = "Boulevard Saint-Laurent Nord",
                            Name = "Saint-Laurent",
                            RouteNumber = "55",
                            StartPoint = "Terminus Berri-UQAM"
                        },
                        new
                        {
                            Id = 11,
                            EndPoint = "Pie-IX / Sauvé",
                            Name = "Saint-Michel",
                            RouteNumber = "67",
                            StartPoint = "Metro Saint-Michel"
                        },
                        new
                        {
                            Id = 12,
                            EndPoint = "Henri-Bourassa / O'Brien",
                            Name = "Gouin",
                            RouteNumber = "69",
                            StartPoint = "Gouin Est / Langelier"
                        },
                        new
                        {
                            Id = 13,
                            EndPoint = "Parc / Jean-Talon",
                            Name = "Du Parc",
                            RouteNumber = "80",
                            StartPoint = "Metro Place-des-Arts"
                        },
                        new
                        {
                            Id = 14,
                            EndPoint = "Lachine",
                            Name = "Saint-Jacques",
                            RouteNumber = "90",
                            StartPoint = "Metro Lionel-Groulx"
                        },
                        new
                        {
                            Id = 15,
                            EndPoint = "Pie-IX / Rosemont",
                            Name = "Mont-Royal",
                            RouteNumber = "97",
                            StartPoint = "Metro Mont-Royal"
                        },
                        new
                        {
                            Id = 16,
                            EndPoint = "Concordia Loyola Campus",
                            Name = "Monkland",
                            RouteNumber = "103",
                            StartPoint = "Metro Villa-Maria"
                        },
                        new
                        {
                            Id = 17,
                            EndPoint = "Concordia Loyola Campus",
                            Name = "Sherbrooke (NDG)",
                            RouteNumber = "105",
                            StartPoint = "Metro Vendôme"
                        },
                        new
                        {
                            Id = 18,
                            EndPoint = "Terminus LaSalle",
                            Name = "Newman",
                            RouteNumber = "106",
                            StartPoint = "Angrignon"
                        },
                        new
                        {
                            Id = 19,
                            EndPoint = "Metro Côte-Vertu",
                            Name = "Sauvé / Côte-Vertu",
                            RouteNumber = "121",
                            StartPoint = "Metro Sauvé"
                        },
                        new
                        {
                            Id = 20,
                            EndPoint = "Metro Guy-Concordia",
                            Name = "Côte-des-Neiges",
                            RouteNumber = "165",
                            StartPoint = "Metro Snowdon"
                        },
                        new
                        {
                            Id = 21,
                            EndPoint = "Henri-Bourassa Ouest / Bois-Franc",
                            Name = "Henri-Bourassa",
                            RouteNumber = "171",
                            StartPoint = "Henri-Bourassa Est"
                        },
                        new
                        {
                            Id = 22,
                            EndPoint = "Sainte-Anne-de-Bellevue",
                            Name = "Bord-du-Lac",
                            RouteNumber = "211",
                            StartPoint = "Metro Lionel-Groulx"
                        },
                        new
                        {
                            Id = 23,
                            EndPoint = "Henri-Bourassa Est",
                            Name = "Express Pie-IX",
                            RouteNumber = "439",
                            StartPoint = "Metro Pie-IX"
                        },
                        new
                        {
                            Id = 24,
                            EndPoint = "Terminus Berri-UQAM",
                            Name = "Express Aéroport / Centre-Ville",
                            RouteNumber = "747",
                            StartPoint = "YUL Montreal-Trudeau"
                        });
                });

            modelBuilder.Entity("CityTransport.Data.Models.BusStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusStops");
                });
#pragma warning restore 612, 618
        }
    }
}
